# c. 06/25/2022
# tom brzyzek

# Equilizer UI File, generated Python code from QTDesigner UI tool & modified.

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QLabel, QLineEdit,
    QMainWindow, QPushButton, QRadioButton, QSizePolicy,
    QSlider, QStatusBar, QVBoxLayout, QWidget)

# from mplwidget import MplWidget #DEVC - Remove? matlabplot widget reference.

class Ui_Equilizer(object):
    def setupUi(self, Equilizer):
        if not Equilizer.objectName():
            Equilizer.setObjectName(u"Equilizer")
        Equilizer.resize(1082, 620)
        self.centralwidget = QWidget(Equilizer)
        self.centralwidget.setObjectName(u"centralwidget")

        self.centralwidget.setStyleSheet("background-color: silver")

        self.labeldB = QLabel(self.centralwidget)
        self.labeldB.setObjectName(u"labeldB")
        self.labeldB.setGeometry(QRect(0, 379, 21, 16))
        self.labeldB.setAlignment(Qt.AlignCenter)

        self.labelpos6 = QLabel(self.centralwidget)
        self.labelpos6.setObjectName(u"labelpos6")
        self.labelpos6.setGeometry(QRect(0, 399, 21, 16))
        self.labelpos6.setAlignment(Qt.AlignCenter)

        self.labelpos3 = QLabel(self.centralwidget)
        self.labelpos3.setObjectName(u"labelpos3")
        self.labelpos3.setGeometry(QRect(0, 438, 21, 16))
        self.labelpos3.setAlignment(Qt.AlignCenter)

        self.labelneg3 = QLabel(self.centralwidget)
        self.labelneg3.setObjectName(u"labelneg3")
        self.labelneg3.setGeometry(QRect(0, 516, 21, 16))
        self.labelneg3.setAlignment(Qt.AlignCenter)

        self.labelneg6 = QLabel(self.centralwidget)
        self.labelneg6.setObjectName(u"labelneg6")
        self.labelneg6.setGeometry(QRect(0, 553, 21, 16))
        self.labelneg6.setAlignment(Qt.AlignCenter)

        self.labelzero = QLabel(self.centralwidget)
        self.labelzero.setObjectName(u"labelzero")
        self.labelzero.setGeometry(QRect(0, 475, 21, 20))
        self.labelzero.setAlignment(Qt.AlignCenter)

        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(20, 400, 1046, 191))
        self.eqSliderLayout = QHBoxLayout(self.layoutWidget)
        self.eqSliderLayout.setObjectName(u"eqSliderLayout")
        self.eqSliderLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout25Hz = QVBoxLayout()
        self.verticalLayout25Hz.setObjectName(u"verticalLayout25Hz")
        self.verticalSlider25Hz = QSlider(self.layoutWidget)
        self.verticalSlider25Hz.setObjectName(u"verticalSlider25Hz")
        self.verticalSlider25Hz.setMinimum(-6)
        self.verticalSlider25Hz.setMaximum(6)
        self.verticalSlider25Hz.setSingleStep(1)
        self.verticalSlider25Hz.setPageStep(1)
        self.verticalSlider25Hz.setValue(0)
        self.verticalSlider25Hz.setSliderPosition(0)
        self.verticalSlider25Hz.setOrientation(Qt.Vertical)
        self.verticalSlider25Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider25Hz.setTickInterval(1)
        self.verticalLayout25Hz.addWidget(self.verticalSlider25Hz)
        self.label25Hz = QLabel(self.layoutWidget)
        self.label25Hz.setObjectName(u"label25Hz")
        self.label25Hz.setLayoutDirection(Qt.LeftToRight)
        self.label25Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout25Hz.addWidget(self.label25Hz)
        self.eqSliderLayout.addLayout(self.verticalLayout25Hz)

        self.verticalLayout31Hz = QVBoxLayout()
        self.verticalLayout31Hz.setObjectName(u"verticalLayout31Hz")
        self.verticalSlider31Hz = QSlider(self.layoutWidget)
        self.verticalSlider31Hz.setObjectName(u"verticalSlider31Hz")
        self.verticalSlider31Hz.setMinimum(-6)
        self.verticalSlider31Hz.setMaximum(6)
        self.verticalSlider31Hz.setSingleStep(1)
        self.verticalSlider31Hz.setPageStep(1)
        self.verticalSlider31Hz.setValue(0)
        self.verticalSlider31Hz.setSliderPosition(0)
        self.verticalSlider31Hz.setOrientation(Qt.Vertical)
        self.verticalSlider31Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider31Hz.setTickInterval(1)
        self.verticalLayout31Hz.addWidget(self.verticalSlider31Hz)
        self.label31Hz = QLabel(self.layoutWidget)
        self.label31Hz.setObjectName(u"label31Hz")
        self.label31Hz.setLayoutDirection(Qt.LeftToRight)
        self.label31Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout31Hz.addWidget(self.label31Hz)
        self.eqSliderLayout.addLayout(self.verticalLayout31Hz)

        self.verticalLayout40Hz = QVBoxLayout()
        self.verticalLayout40Hz.setObjectName(u"verticalLayout40Hz")
        self.verticalSlider40Hz = QSlider(self.layoutWidget)
        self.verticalSlider40Hz.setObjectName(u"verticalSlider40Hz")
        self.verticalSlider40Hz.setMinimum(-6)
        self.verticalSlider40Hz.setMaximum(6)
        self.verticalSlider40Hz.setSingleStep(1)
        self.verticalSlider40Hz.setPageStep(1)
        self.verticalSlider40Hz.setValue(0)
        self.verticalSlider40Hz.setSliderPosition(0)
        self.verticalSlider40Hz.setOrientation(Qt.Vertical)
        self.verticalSlider40Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider40Hz.setTickInterval(1)
        self.verticalLayout40Hz.addWidget(self.verticalSlider40Hz)
        self.label40Hz = QLabel(self.layoutWidget)
        self.label40Hz.setObjectName(u"label40Hz")
        self.label40Hz.setLayoutDirection(Qt.LeftToRight)
        self.label40Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout40Hz.addWidget(self.label40Hz)
        self.eqSliderLayout.addLayout(self.verticalLayout40Hz)

        self.verticalLayout50Hz = QVBoxLayout()
        self.verticalLayout50Hz.setObjectName(u"verticalLayout50Hz")
        self.verticalSlider50Hz = QSlider(self.layoutWidget)
        self.verticalSlider50Hz.setObjectName(u"verticalSlider50Hz")
        self.verticalSlider50Hz.setMinimum(-6)
        self.verticalSlider50Hz.setMaximum(6)
        self.verticalSlider50Hz.setSingleStep(1)
        self.verticalSlider50Hz.setPageStep(1)
        self.verticalSlider50Hz.setValue(0)
        self.verticalSlider50Hz.setSliderPosition(0)
        self.verticalSlider50Hz.setOrientation(Qt.Vertical)
        self.verticalSlider50Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider50Hz.setTickInterval(1)
        self.verticalLayout50Hz.addWidget(self.verticalSlider50Hz)
        self.label50Hz = QLabel(self.layoutWidget)
        self.label50Hz.setObjectName(u"label50Hz")
        self.label50Hz.setLayoutDirection(Qt.LeftToRight)
        self.label50Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout50Hz.addWidget(self.label50Hz)
        self.eqSliderLayout.addLayout(self.verticalLayout50Hz)

        self.verticalLayout63Hz = QVBoxLayout()
        self.verticalLayout63Hz.setObjectName(u"verticalLayout63Hz")
        self.verticalSlider63Hz = QSlider(self.layoutWidget)
        self.verticalSlider63Hz.setObjectName(u"verticalSlider63Hz")
        self.verticalSlider63Hz.setMinimum(-6)
        self.verticalSlider63Hz.setMaximum(6)
        self.verticalSlider63Hz.setSingleStep(1)
        self.verticalSlider63Hz.setPageStep(1)
        self.verticalSlider63Hz.setValue(0)
        self.verticalSlider63Hz.setSliderPosition(0)
        self.verticalSlider63Hz.setOrientation(Qt.Vertical)
        self.verticalSlider63Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider63Hz.setTickInterval(1)
        self.verticalLayout63Hz.addWidget(self.verticalSlider63Hz)
        self.label63Hz = QLabel(self.layoutWidget)
        self.label63Hz.setObjectName(u"label63Hz")
        self.label63Hz.setLayoutDirection(Qt.LeftToRight)
        self.label63Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout63Hz.addWidget(self.label63Hz)
        self.eqSliderLayout.addLayout(self.verticalLayout63Hz)

        self.verticalLayout80Hz = QVBoxLayout()
        self.verticalLayout80Hz.setObjectName(u"verticalLayout80Hz")
        self.verticalSlider80Hz = QSlider(self.layoutWidget)
        self.verticalSlider80Hz.setObjectName(u"verticalSlider80Hz")
        self.verticalSlider80Hz.setMinimum(-6)
        self.verticalSlider80Hz.setMaximum(6)
        self.verticalSlider80Hz.setSingleStep(1)
        self.verticalSlider80Hz.setPageStep(1)
        self.verticalSlider80Hz.setValue(0)
        self.verticalSlider80Hz.setSliderPosition(0)
        self.verticalSlider80Hz.setOrientation(Qt.Vertical)
        self.verticalSlider80Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider80Hz.setTickInterval(1)
        self.verticalLayout80Hz.addWidget(self.verticalSlider80Hz)
        self.label80Hz = QLabel(self.layoutWidget)
        self.label80Hz.setObjectName(u"label80Hz")
        self.label80Hz.setLayoutDirection(Qt.LeftToRight)
        self.label80Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout80Hz.addWidget(self.label80Hz)
        self.eqSliderLayout.addLayout(self.verticalLayout80Hz)

        self.verticalLayout100Hz = QVBoxLayout()
        self.verticalLayout100Hz.setObjectName(u"verticalLayout100Hz")
        self.verticalSlider100Hz = QSlider(self.layoutWidget)
        self.verticalSlider100Hz.setObjectName(u"verticalSlider100Hz")
        self.verticalSlider100Hz.setMinimum(-6)
        self.verticalSlider100Hz.setMaximum(6)
        self.verticalSlider100Hz.setSingleStep(1)
        self.verticalSlider100Hz.setPageStep(1)
        self.verticalSlider100Hz.setValue(0)
        self.verticalSlider100Hz.setSliderPosition(0)
        self.verticalSlider100Hz.setOrientation(Qt.Vertical)
        self.verticalSlider100Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider100Hz.setTickInterval(1)
        self.verticalLayout100Hz.addWidget(self.verticalSlider100Hz)
        self.label100Hz = QLabel(self.layoutWidget)
        self.label100Hz.setObjectName(u"label100Hz")
        self.label100Hz.setLayoutDirection(Qt.LeftToRight)
        self.label100Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout100Hz.addWidget(self.label100Hz)
        self.eqSliderLayout.addLayout(self.verticalLayout100Hz)

        self.verticalLayout125Hz = QVBoxLayout()
        self.verticalLayout125Hz.setObjectName(u"verticalLayout125Hz")
        self.verticalSlider125Hz = QSlider(self.layoutWidget)
        self.verticalSlider125Hz.setObjectName(u"verticalSlider125Hz")
        self.verticalSlider125Hz.setMinimum(-6)
        self.verticalSlider125Hz.setMaximum(6)
        self.verticalSlider125Hz.setSingleStep(1)
        self.verticalSlider125Hz.setPageStep(1)
        self.verticalSlider125Hz.setValue(0)
        self.verticalSlider125Hz.setSliderPosition(0)
        self.verticalSlider125Hz.setOrientation(Qt.Vertical)
        self.verticalSlider125Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider125Hz.setTickInterval(1)
        self.verticalLayout125Hz.addWidget(self.verticalSlider125Hz)
        self.label125Hz = QLabel(self.layoutWidget)
        self.label125Hz.setObjectName(u"label125Hz")
        self.label125Hz.setLayoutDirection(Qt.LeftToRight)
        self.label125Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout125Hz.addWidget(self.label125Hz)
        self.eqSliderLayout.addLayout(self.verticalLayout125Hz)

        self.verticalLayout160Hz = QVBoxLayout()
        self.verticalLayout160Hz.setObjectName(u"verticalLayout160Hz")
        self.verticalSlider160Hz = QSlider(self.layoutWidget)
        self.verticalSlider160Hz.setObjectName(u"verticalSlider160Hz")
        self.verticalSlider160Hz.setMinimum(-6)
        self.verticalSlider160Hz.setMaximum(6)
        self.verticalSlider160Hz.setSingleStep(1)
        self.verticalSlider160Hz.setPageStep(1)
        self.verticalSlider160Hz.setValue(0)
        self.verticalSlider160Hz.setSliderPosition(0)
        self.verticalSlider160Hz.setOrientation(Qt.Vertical)
        self.verticalSlider160Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider160Hz.setTickInterval(1)
        self.verticalLayout160Hz.addWidget(self.verticalSlider160Hz)
        self.label160Hz = QLabel(self.layoutWidget)
        self.label160Hz.setObjectName(u"label160Hz")
        self.label160Hz.setLayoutDirection(Qt.LeftToRight)
        self.label160Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout160Hz.addWidget(self.label160Hz)
        self.eqSliderLayout.addLayout(self.verticalLayout160Hz)

        self.verticalLayout200Hz = QVBoxLayout()
        self.verticalLayout200Hz.setObjectName(u"verticalLayout200Hz")
        self.verticalSlider200Hz = QSlider(self.layoutWidget)
        self.verticalSlider200Hz.setObjectName(u"verticalSlider200Hz")
        self.verticalSlider200Hz.setMinimum(-6)
        self.verticalSlider200Hz.setMaximum(6)
        self.verticalSlider200Hz.setSingleStep(1)
        self.verticalSlider200Hz.setPageStep(1)
        self.verticalSlider200Hz.setValue(0)
        self.verticalSlider200Hz.setSliderPosition(0)
        self.verticalSlider200Hz.setOrientation(Qt.Vertical)
        self.verticalSlider200Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider200Hz.setTickInterval(1)
        self.verticalLayout200Hz.addWidget(self.verticalSlider200Hz)
        self.label200Hz = QLabel(self.layoutWidget)
        self.label200Hz.setObjectName(u"label200Hz")
        self.label200Hz.setLayoutDirection(Qt.LeftToRight)
        self.label200Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout200Hz.addWidget(self.label200Hz)
        self.eqSliderLayout.addLayout(self.verticalLayout200Hz)

        self.verticalLayout250Hz = QVBoxLayout()
        self.verticalLayout250Hz.setObjectName(u"verticalLayout250Hz")
        self.verticalSlider250Hz = QSlider(self.layoutWidget)
        self.verticalSlider250Hz.setObjectName(u"verticalSlider250Hz")
        self.verticalSlider250Hz.setMinimum(-6)
        self.verticalSlider250Hz.setMaximum(6)
        self.verticalSlider250Hz.setSingleStep(1)
        self.verticalSlider250Hz.setPageStep(1)
        self.verticalSlider250Hz.setValue(0)
        self.verticalSlider250Hz.setSliderPosition(0)
        self.verticalSlider250Hz.setOrientation(Qt.Vertical)
        self.verticalSlider250Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider250Hz.setTickInterval(1)
        self.verticalLayout250Hz.addWidget(self.verticalSlider250Hz)
        self.label250Hz = QLabel(self.layoutWidget)
        self.label250Hz.setObjectName(u"label250Hz")
        self.label250Hz.setLayoutDirection(Qt.LeftToRight)
        self.label250Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout250Hz.addWidget(self.label250Hz)
        self.eqSliderLayout.addLayout(self.verticalLayout250Hz)

        self.verticalLayout315Hz = QVBoxLayout()
        self.verticalLayout315Hz.setObjectName(u"verticalLayout315Hz")
        self.verticalSlider315Hz = QSlider(self.layoutWidget)
        self.verticalSlider315Hz.setObjectName(u"verticalSlider315Hz")
        self.verticalSlider315Hz.setMinimum(-6)
        self.verticalSlider315Hz.setMaximum(6)
        self.verticalSlider315Hz.setSingleStep(1)
        self.verticalSlider315Hz.setPageStep(1)
        self.verticalSlider315Hz.setValue(0)
        self.verticalSlider315Hz.setSliderPosition(0)
        self.verticalSlider315Hz.setOrientation(Qt.Vertical)
        self.verticalSlider315Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider315Hz.setTickInterval(1)
        self.verticalLayout315Hz.addWidget(self.verticalSlider315Hz)
        self.label315Hz = QLabel(self.layoutWidget)
        self.label315Hz.setObjectName(u"label315Hz")
        self.label315Hz.setLayoutDirection(Qt.LeftToRight)
        self.label315Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout315Hz.addWidget(self.label315Hz)
        self.eqSliderLayout.addLayout(self.verticalLayout315Hz)

        self.verticalLayout400Hz = QVBoxLayout()
        self.verticalLayout400Hz.setObjectName(u"verticalLayout400Hz")
        self.verticalSlider400Hz = QSlider(self.layoutWidget)
        self.verticalSlider400Hz.setObjectName(u"verticalSlider400Hz")
        self.verticalSlider400Hz.setMinimum(-6)
        self.verticalSlider400Hz.setMaximum(6)
        self.verticalSlider400Hz.setSingleStep(1)
        self.verticalSlider400Hz.setPageStep(1)
        self.verticalSlider400Hz.setValue(0)
        self.verticalSlider400Hz.setSliderPosition(0)
        self.verticalSlider400Hz.setOrientation(Qt.Vertical)
        self.verticalSlider400Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider400Hz.setTickInterval(1)
        self.verticalLayout400Hz.addWidget(self.verticalSlider400Hz)
        self.label400Hz = QLabel(self.layoutWidget)
        self.label400Hz.setObjectName(u"label400Hz")
        self.label400Hz.setLayoutDirection(Qt.LeftToRight)
        self.label400Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout400Hz.addWidget(self.label400Hz)
        self.eqSliderLayout.addLayout(self.verticalLayout400Hz)

        self.verticalLayout500Hz = QVBoxLayout()
        self.verticalLayout500Hz.setObjectName(u"verticalLayout500Hz")
        self.verticalSlider500Hz = QSlider(self.layoutWidget)
        self.verticalSlider500Hz.setObjectName(u"verticalSlider500Hz")
        self.verticalSlider500Hz.setMinimum(-6)
        self.verticalSlider500Hz.setMaximum(6)
        self.verticalSlider500Hz.setSingleStep(1)
        self.verticalSlider500Hz.setPageStep(1)
        self.verticalSlider500Hz.setValue(0)
        self.verticalSlider500Hz.setSliderPosition(0)
        self.verticalSlider500Hz.setOrientation(Qt.Vertical)
        self.verticalSlider500Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider500Hz.setTickInterval(1)
        self.verticalLayout500Hz.addWidget(self.verticalSlider500Hz)
        self.label500Hz = QLabel(self.layoutWidget)
        self.label500Hz.setObjectName(u"label500Hz")
        self.label500Hz.setLayoutDirection(Qt.LeftToRight)
        self.label500Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout500Hz.addWidget(self.label500Hz)
        self.eqSliderLayout.addLayout(self.verticalLayout500Hz)

        self.verticalLayout630Hz = QVBoxLayout()
        self.verticalLayout630Hz.setObjectName(u"verticalLayout630Hz")
        self.verticalSlider630Hz = QSlider(self.layoutWidget)
        self.verticalSlider630Hz.setObjectName(u"verticalSlider630Hz")
        self.verticalSlider630Hz.setMinimum(-6)
        self.verticalSlider630Hz.setMaximum(6)
        self.verticalSlider630Hz.setSingleStep(1)
        self.verticalSlider630Hz.setPageStep(1)
        self.verticalSlider630Hz.setValue(0)
        self.verticalSlider630Hz.setSliderPosition(0)
        self.verticalSlider630Hz.setOrientation(Qt.Vertical)
        self.verticalSlider630Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider630Hz.setTickInterval(1)
        self.verticalLayout630Hz.addWidget(self.verticalSlider630Hz)
        self.label630Hz = QLabel(self.layoutWidget)
        self.label630Hz.setObjectName(u"label630Hz")
        self.label630Hz.setLayoutDirection(Qt.LeftToRight)
        self.label630Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout630Hz.addWidget(self.label630Hz)
        self.eqSliderLayout.addLayout(self.verticalLayout630Hz)

        self.verticalLayout800Hz = QVBoxLayout()
        self.verticalLayout800Hz.setObjectName(u"verticalLayout800Hz")
        self.verticalSlider800Hz = QSlider(self.layoutWidget)
        self.verticalSlider800Hz.setObjectName(u"verticalSlider800Hz")
        self.verticalSlider800Hz.setMinimum(-6)
        self.verticalSlider800Hz.setMaximum(6)
        self.verticalSlider800Hz.setSingleStep(1)
        self.verticalSlider800Hz.setPageStep(1)
        self.verticalSlider800Hz.setValue(0)
        self.verticalSlider800Hz.setSliderPosition(0)
        self.verticalSlider800Hz.setOrientation(Qt.Vertical)
        self.verticalSlider800Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider800Hz.setTickInterval(1)
        self.verticalLayout800Hz.addWidget(self.verticalSlider800Hz)
        self.label800Hz = QLabel(self.layoutWidget)
        self.label800Hz.setObjectName(u"label800Hz")
        self.label800Hz.setLayoutDirection(Qt.LeftToRight)
        self.label800Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout800Hz.addWidget(self.label800Hz)
        self.eqSliderLayout.addLayout(self.verticalLayout800Hz)

        self.verticalLayout1kHz = QVBoxLayout()
        self.verticalLayout1kHz.setObjectName(u"verticalLayout1kHz")
        self.verticalSlider1kHz = QSlider(self.layoutWidget)
        self.verticalSlider1kHz.setObjectName(u"verticalSlider1kHz")
        self.verticalSlider1kHz.setMinimum(-6)
        self.verticalSlider1kHz.setMaximum(6)
        self.verticalSlider1kHz.setSingleStep(1)
        self.verticalSlider1kHz.setPageStep(1)
        self.verticalSlider1kHz.setValue(0)
        self.verticalSlider1kHz.setSliderPosition(0)
        self.verticalSlider1kHz.setOrientation(Qt.Vertical)
        self.verticalSlider1kHz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider1kHz.setTickInterval(1)
        self.verticalLayout1kHz.addWidget(self.verticalSlider1kHz)
        self.label1kHz = QLabel(self.layoutWidget)
        self.label1kHz.setObjectName(u"label1kHz")
        self.label1kHz.setLayoutDirection(Qt.LeftToRight)
        self.label1kHz.setAlignment(Qt.AlignCenter)
        self.verticalLayout1kHz.addWidget(self.label1kHz)
        self.eqSliderLayout.addLayout(self.verticalLayout1kHz)

        self.verticalLayout1k25Hz = QVBoxLayout()
        self.verticalLayout1k25Hz.setObjectName(u"verticalLayout1k25Hz")
        self.verticalSlider1k25Hz = QSlider(self.layoutWidget)
        self.verticalSlider1k25Hz.setObjectName(u"verticalSlider1k25Hz")
        self.verticalSlider1k25Hz.setMinimum(-6)
        self.verticalSlider1k25Hz.setMaximum(6)
        self.verticalSlider1k25Hz.setSingleStep(1)
        self.verticalSlider1k25Hz.setPageStep(1)
        self.verticalSlider1k25Hz.setValue(0)
        self.verticalSlider1k25Hz.setSliderPosition(0)
        self.verticalSlider1k25Hz.setOrientation(Qt.Vertical)
        self.verticalSlider1k25Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider1k25Hz.setTickInterval(1)
        self.verticalLayout1k25Hz.addWidget(self.verticalSlider1k25Hz)
        self.label1k25Hz = QLabel(self.layoutWidget)
        self.label1k25Hz.setObjectName(u"label1k25Hz")
        self.label1k25Hz.setLayoutDirection(Qt.LeftToRight)
        self.label1k25Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout1k25Hz.addWidget(self.label1k25Hz)
        self.eqSliderLayout.addLayout(self.verticalLayout1k25Hz)

        self.verticalLayout1k6Hz = QVBoxLayout()
        self.verticalLayout1k6Hz.setObjectName(u"verticalLayout1k6Hz")
        self.verticalSlider1k6Hz = QSlider(self.layoutWidget)
        self.verticalSlider1k6Hz.setObjectName(u"verticalSlider1k6Hz")
        self.verticalSlider1k6Hz.setMinimum(-6)
        self.verticalSlider1k6Hz.setMaximum(6)
        self.verticalSlider1k6Hz.setSingleStep(1)
        self.verticalSlider1k6Hz.setPageStep(1)
        self.verticalSlider1k6Hz.setValue(0)
        self.verticalSlider1k6Hz.setSliderPosition(0)
        self.verticalSlider1k6Hz.setOrientation(Qt.Vertical)
        self.verticalSlider1k6Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider1k6Hz.setTickInterval(1)
        self.verticalLayout1k6Hz.addWidget(self.verticalSlider1k6Hz)
        self.label1k6Hz = QLabel(self.layoutWidget)
        self.label1k6Hz.setObjectName(u"label1k6Hz")
        self.label1k6Hz.setLayoutDirection(Qt.LeftToRight)
        self.label1k6Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout1k6Hz.addWidget(self.label1k6Hz)
        self.eqSliderLayout.addLayout(self.verticalLayout1k6Hz)

        self.verticalLayout2kHz = QVBoxLayout()
        self.verticalLayout2kHz.setObjectName(u"verticalLayout2kHz")
        self.verticalSlider2kHz = QSlider(self.layoutWidget)
        self.verticalSlider2kHz.setObjectName(u"verticalSlider2kHz")
        self.verticalSlider2kHz.setMinimum(-6)
        self.verticalSlider2kHz.setMaximum(6)
        self.verticalSlider2kHz.setSingleStep(1)
        self.verticalSlider2kHz.setPageStep(1)
        self.verticalSlider2kHz.setValue(0)
        self.verticalSlider2kHz.setSliderPosition(0)
        self.verticalSlider2kHz.setOrientation(Qt.Vertical)
        self.verticalSlider2kHz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider2kHz.setTickInterval(1)
        self.verticalLayout2kHz.addWidget(self.verticalSlider2kHz)
        self.label2kHz = QLabel(self.layoutWidget)
        self.label2kHz.setObjectName(u"label2kHz")
        self.label2kHz.setLayoutDirection(Qt.LeftToRight)
        self.label2kHz.setAlignment(Qt.AlignCenter)
        self.verticalLayout2kHz.addWidget(self.label2kHz)
        self.eqSliderLayout.addLayout(self.verticalLayout2kHz)

        self.verticalLayout2k5Hz = QVBoxLayout()
        self.verticalLayout2k5Hz.setObjectName(u"verticalLayout2k5Hz")
        self.verticalSlider2k5Hz = QSlider(self.layoutWidget)
        self.verticalSlider2k5Hz.setObjectName(u"verticalSlider2k5Hz")
        self.verticalSlider2k5Hz.setMinimum(-6)
        self.verticalSlider2k5Hz.setMaximum(6)
        self.verticalSlider2k5Hz.setSingleStep(1)
        self.verticalSlider2k5Hz.setPageStep(1)
        self.verticalSlider2k5Hz.setValue(0)
        self.verticalSlider2k5Hz.setSliderPosition(0)
        self.verticalSlider2k5Hz.setOrientation(Qt.Vertical)
        self.verticalSlider2k5Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider2k5Hz.setTickInterval(1)
        self.verticalLayout2k5Hz.addWidget(self.verticalSlider2k5Hz)
        self.label2k5Hz = QLabel(self.layoutWidget)
        self.label2k5Hz.setObjectName(u"label2k5Hz")
        self.label2k5Hz.setLayoutDirection(Qt.LeftToRight)
        self.label2k5Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout2k5Hz.addWidget(self.label2k5Hz)
        self.eqSliderLayout.addLayout(self.verticalLayout2k5Hz)

        self.verticalLayout3k15Hz = QVBoxLayout()
        self.verticalLayout3k15Hz.setObjectName(u"verticalLayout3k15Hz")
        self.verticalSlider3k15Hz = QSlider(self.layoutWidget)
        self.verticalSlider3k15Hz.setObjectName(u"verticalSlider3k15Hz")
        self.verticalSlider3k15Hz.setMinimum(-6)
        self.verticalSlider3k15Hz.setMaximum(6)
        self.verticalSlider3k15Hz.setSingleStep(1)
        self.verticalSlider3k15Hz.setPageStep(1)
        self.verticalSlider3k15Hz.setValue(0)
        self.verticalSlider3k15Hz.setSliderPosition(0)
        self.verticalSlider3k15Hz.setOrientation(Qt.Vertical)
        self.verticalSlider3k15Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider3k15Hz.setTickInterval(1)
        self.verticalLayout3k15Hz.addWidget(self.verticalSlider3k15Hz)
        self.label3k15Hz = QLabel(self.layoutWidget)
        self.label3k15Hz.setObjectName(u"label3k15Hz")
        self.label3k15Hz.setLayoutDirection(Qt.LeftToRight)
        self.label3k15Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout3k15Hz.addWidget(self.label3k15Hz)

        self.eqSliderLayout.addLayout(self.verticalLayout3k15Hz)
        self.verticalLayout4kHz = QVBoxLayout()
        self.verticalLayout4kHz.setObjectName(u"verticalLayout4kHz")
        self.verticalSlider4kHz = QSlider(self.layoutWidget)
        self.verticalSlider4kHz.setObjectName(u"verticalSlider4kHz")
        self.verticalSlider4kHz.setMinimum(-6)
        self.verticalSlider4kHz.setMaximum(6)
        self.verticalSlider4kHz.setSingleStep(1)
        self.verticalSlider4kHz.setPageStep(1)
        self.verticalSlider4kHz.setValue(0)
        self.verticalSlider4kHz.setSliderPosition(0)
        self.verticalSlider4kHz.setOrientation(Qt.Vertical)
        self.verticalSlider4kHz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider4kHz.setTickInterval(1)
        self.verticalLayout4kHz.addWidget(self.verticalSlider4kHz)
        self.label4kHz = QLabel(self.layoutWidget)
        self.label4kHz.setObjectName(u"label4kHz")
        self.label4kHz.setLayoutDirection(Qt.LeftToRight)
        self.label4kHz.setAlignment(Qt.AlignCenter)
        self.verticalLayout4kHz.addWidget(self.label4kHz)
        self.eqSliderLayout.addLayout(self.verticalLayout4kHz)

        self.verticalLayout5kHz = QVBoxLayout()
        self.verticalLayout5kHz.setObjectName(u"verticalLayout5kHz")
        self.verticalSlider5kHz = QSlider(self.layoutWidget)
        self.verticalSlider5kHz.setObjectName(u"verticalSlider5kHz")
        self.verticalSlider5kHz.setMinimum(-6)
        self.verticalSlider5kHz.setMaximum(6)
        self.verticalSlider5kHz.setSingleStep(1)
        self.verticalSlider5kHz.setPageStep(1)
        self.verticalSlider5kHz.setValue(0)
        self.verticalSlider5kHz.setSliderPosition(0)
        self.verticalSlider5kHz.setOrientation(Qt.Vertical)
        self.verticalSlider5kHz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider5kHz.setTickInterval(1)
        self.verticalLayout5kHz.addWidget(self.verticalSlider5kHz)
        self.label5kHz = QLabel(self.layoutWidget)
        self.label5kHz.setObjectName(u"label5kHz")
        self.label5kHz.setLayoutDirection(Qt.LeftToRight)
        self.label5kHz.setAlignment(Qt.AlignCenter)
        self.verticalLayout5kHz.addWidget(self.label5kHz)
        self.eqSliderLayout.addLayout(self.verticalLayout5kHz)

        self.verticalLayout6k3Hz = QVBoxLayout()
        self.verticalLayout6k3Hz.setObjectName(u"verticalLayout6k3Hz")
        self.verticalSlider6k3Hz = QSlider(self.layoutWidget)
        self.verticalSlider6k3Hz.setObjectName(u"verticalSlider6k3Hz")
        self.verticalSlider6k3Hz.setMinimum(-6)
        self.verticalSlider6k3Hz.setMaximum(6)
        self.verticalSlider6k3Hz.setSingleStep(1)
        self.verticalSlider6k3Hz.setPageStep(1)
        self.verticalSlider6k3Hz.setValue(0)
        self.verticalSlider6k3Hz.setSliderPosition(0)
        self.verticalSlider6k3Hz.setOrientation(Qt.Vertical)
        self.verticalSlider6k3Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider6k3Hz.setTickInterval(1)
        self.verticalLayout6k3Hz.addWidget(self.verticalSlider6k3Hz)
        self.label6k3Hz = QLabel(self.layoutWidget)
        self.label6k3Hz.setObjectName(u"label6k3Hz")
        self.label6k3Hz.setLayoutDirection(Qt.LeftToRight)
        self.label6k3Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout6k3Hz.addWidget(self.label6k3Hz)
        self.eqSliderLayout.addLayout(self.verticalLayout6k3Hz)

        self.verticalLayout8kHz = QVBoxLayout()
        self.verticalLayout8kHz.setObjectName(u"verticalLayout8kHz")
        self.verticalSlider8kHz = QSlider(self.layoutWidget)
        self.verticalSlider8kHz.setObjectName(u"verticalSlider8kHz")
        self.verticalSlider8kHz.setMinimum(-6)
        self.verticalSlider8kHz.setMaximum(6)
        self.verticalSlider8kHz.setSingleStep(1)
        self.verticalSlider8kHz.setPageStep(1)
        self.verticalSlider8kHz.setValue(0)
        self.verticalSlider8kHz.setSliderPosition(0)
        self.verticalSlider8kHz.setOrientation(Qt.Vertical)
        self.verticalSlider8kHz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider8kHz.setTickInterval(1)
        self.verticalLayout8kHz.addWidget(self.verticalSlider8kHz)
        self.label8kHz = QLabel(self.layoutWidget)
        self.label8kHz.setObjectName(u"label8kHz")
        self.label8kHz.setLayoutDirection(Qt.LeftToRight)
        self.label8kHz.setAlignment(Qt.AlignCenter)
        self.verticalLayout8kHz.addWidget(self.label8kHz)
        self.eqSliderLayout.addLayout(self.verticalLayout8kHz)

        self.verticalLayout10kHz = QVBoxLayout()
        self.verticalLayout10kHz.setObjectName(u"verticalLayout10kHz")
        self.verticalSlider10kHz = QSlider(self.layoutWidget)
        self.verticalSlider10kHz.setObjectName(u"verticalSlider10kHz")
        self.verticalSlider10kHz.setMinimum(-6)
        self.verticalSlider10kHz.setMaximum(6)
        self.verticalSlider10kHz.setSingleStep(1)
        self.verticalSlider10kHz.setPageStep(1)
        self.verticalSlider10kHz.setValue(0)
        self.verticalSlider10kHz.setSliderPosition(0)
        self.verticalSlider10kHz.setOrientation(Qt.Vertical)
        self.verticalSlider10kHz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider10kHz.setTickInterval(1)
        self.verticalLayout10kHz.addWidget(self.verticalSlider10kHz)
        self.label10kHz = QLabel(self.layoutWidget)
        self.label10kHz.setObjectName(u"label10kHz")
        self.label10kHz.setLayoutDirection(Qt.LeftToRight)
        self.label10kHz.setAlignment(Qt.AlignCenter)
        self.verticalLayout10kHz.addWidget(self.label10kHz)
        self.eqSliderLayout.addLayout(self.verticalLayout10kHz)

        self.verticalLayout12k5Hz = QVBoxLayout()
        self.verticalLayout12k5Hz.setObjectName(u"verticalLayout12k5Hz")
        self.verticalSlider12k5Hz = QSlider(self.layoutWidget)
        self.verticalSlider12k5Hz.setObjectName(u"verticalSlider12k5Hz")
        self.verticalSlider12k5Hz.setMinimum(-6)
        self.verticalSlider12k5Hz.setMaximum(6)
        self.verticalSlider12k5Hz.setSingleStep(1)
        self.verticalSlider12k5Hz.setPageStep(1)
        self.verticalSlider12k5Hz.setValue(0)
        self.verticalSlider12k5Hz.setSliderPosition(0)
        self.verticalSlider12k5Hz.setOrientation(Qt.Vertical)
        self.verticalSlider12k5Hz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider12k5Hz.setTickInterval(1)
        self.verticalLayout12k5Hz.addWidget(self.verticalSlider12k5Hz)
        self.label12k5Hz = QLabel(self.layoutWidget)
        self.label12k5Hz.setObjectName(u"label12k5Hz")
        self.label12k5Hz.setLayoutDirection(Qt.LeftToRight)
        self.label12k5Hz.setAlignment(Qt.AlignCenter)
        self.verticalLayout12k5Hz.addWidget(self.label12k5Hz)
        self.eqSliderLayout.addLayout(self.verticalLayout12k5Hz)

        self.verticalLayout16kHz = QVBoxLayout()
        self.verticalLayout16kHz.setObjectName(u"verticalLayout16kHz")
        self.verticalSlider16kHz = QSlider(self.layoutWidget)
        self.verticalSlider16kHz.setObjectName(u"verticalSlider16kHz")
        self.verticalSlider16kHz.setMinimum(-6)
        self.verticalSlider16kHz.setMaximum(6)
        self.verticalSlider16kHz.setSingleStep(1)
        self.verticalSlider16kHz.setPageStep(1)
        self.verticalSlider16kHz.setValue(0)
        self.verticalSlider16kHz.setSliderPosition(0)
        self.verticalSlider16kHz.setOrientation(Qt.Vertical)
        self.verticalSlider16kHz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider16kHz.setTickInterval(1)
        self.verticalLayout16kHz.addWidget(self.verticalSlider16kHz)
        self.label16kHz = QLabel(self.layoutWidget)
        self.label16kHz.setObjectName(u"label16kHz")
        self.label16kHz.setLayoutDirection(Qt.LeftToRight)
        self.label16kHz.setAlignment(Qt.AlignCenter)
        self.verticalLayout16kHz.addWidget(self.label16kHz)
        self.eqSliderLayout.addLayout(self.verticalLayout16kHz)

        self.verticalLayout20kHz = QVBoxLayout()
        self.verticalLayout20kHz.setObjectName(u"verticalLayout20kHz")
        self.verticalSlider20kHz = QSlider(self.layoutWidget)
        self.verticalSlider20kHz.setObjectName(u"verticalSlider20kHz")
        self.verticalSlider20kHz.setMinimum(-6)
        self.verticalSlider20kHz.setMaximum(6)
        self.verticalSlider20kHz.setSingleStep(1)
        self.verticalSlider20kHz.setPageStep(1)
        self.verticalSlider20kHz.setValue(0)
        self.verticalSlider20kHz.setSliderPosition(0)
        self.verticalSlider20kHz.setOrientation(Qt.Vertical)
        self.verticalSlider20kHz.setTickPosition(QSlider.TicksAbove)
        self.verticalSlider20kHz.setTickInterval(1)
        self.verticalLayout20kHz.addWidget(self.verticalSlider20kHz)
        self.label20kHz = QLabel(self.layoutWidget)
        self.label20kHz.setObjectName(u"label20kHz")
        self.label20kHz.setLayoutDirection(Qt.LeftToRight)
        self.label20kHz.setAlignment(Qt.AlignCenter)
        self.verticalLayout20kHz.addWidget(self.label20kHz)
        self.eqSliderLayout.addLayout(self.verticalLayout20kHz)

        self.lineEditFileBrowse = QLineEdit(self.centralwidget)
        self.lineEditFileBrowse.setObjectName(u"lineEditFileBrowse")
        self.lineEditFileBrowse.setGeometry(QRect(20, 20, 341, 22))
        self.lineEditFileBrowse.setStyleSheet("background-color: whitesmoke")
        self.pushButtonFileBrowse = QPushButton(self.centralwidget)
        self.pushButtonFileBrowse.setObjectName(u"pushButtonFileBrowse")
        self.pushButtonFileBrowse.setGeometry(QRect(370, 20, 75, 24))
        self.pushButtonFileImport = QPushButton(self.centralwidget)
        self.pushButtonFileImport.setObjectName(u"pushButtonFileImport")
        self.pushButtonFileImport.setGeometry(QRect(450, 20, 75, 24))
        self.pushButtonReset = QPushButton(self.centralwidget)
        self.pushButtonReset.setObjectName(u"pushButtonFileImport")
        self.pushButtonReset.setGeometry(QRect(530, 20, 75, 24))

        self.frequencyPlotLayout = QVBoxLayout()
        self.frequencyPlotLayout.setObjectName(u"frequencyPlotLayout")
        self.frequencyPlotWidget = QWidget(self.centralwidget) #DEVC MATPLOTLIB
        self.frequencyPlotWidget.setObjectName(u"frequencyPlotWidget")
        self.frequencyPlotWidget.setGeometry(QRect(20, 70, 641, 141))
        self.frequencyPlotWidget.setLayout(self.frequencyPlotLayout)

        self.timePlotLayout = QVBoxLayout()
        self.timePlotLayout.setObjectName(u"timePlotLayout")
        self.timePlotWidget = QWidget(self.centralwidget) #DEVC MATPLOTLIB
        self.timePlotWidget.setObjectName(u"timePlotWidget")
        self.timePlotWidget.setGeometry(QRect(20, 240, 641, 141))
        self.timePlotWidget.setLayout(self.timePlotLayout)

        self.filterPlotWidget = QWidget(self.centralwidget) #DEVC MATPLOTLIB
    
        self.filterPlotWidget.setObjectName(u"filterPlotWidget")
        self.filterPlotWidget.setGeometry(QRect(690, 70, 341, 211))

        self.radioButtonpolezero = QRadioButton(self.centralwidget)
        self.radioButtonpolezero.setObjectName(u"radioButtonpolezero")
        self.radioButtonpolezero.setGeometry(QRect(730, 300, 271, 20))
        self.radioButtonpolezero.setChecked(True)
    
        self.radioButtonfreqdom = QRadioButton(self.centralwidget)
        self.radioButtonfreqdom.setObjectName(u"radioButtonfreqdom")
        self.radioButtonfreqdom.setGeometry(QRect(730, 330, 271, 20))

        self.radioButtontimedom = QRadioButton(self.centralwidget)
        self.radioButtontimedom.setObjectName(u"radioButtontimedom")
        self.radioButtontimedom.setGeometry(QRect(730, 360, 271, 20))

        self.labelFilterPlot = QLabel(self.centralwidget)
        self.labelFilterPlot.setObjectName(u"labelFilterPlot")
        self.labelFilterPlot.setGeometry(QRect(690, 50, 81, 16))

        self.labelFreqPlot = QLabel(self.centralwidget)
        self.labelFreqPlot.setObjectName(u"labelFreqPlot")
        self.labelFreqPlot.setGeometry(QRect(20, 50, 115 , 16))

        self.labelTimePlot = QLabel(self.centralwidget)
        self.labelTimePlot.setObjectName(u"labelTimePlot")
        self.labelTimePlot.setGeometry(QRect(20, 220, 81, 16))

        Equilizer.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(Equilizer)
        self.statusbar.setObjectName(u"statusbar")
        Equilizer.setStatusBar(self.statusbar)

        self.retranslateUi(Equilizer)

        QMetaObject.connectSlotsByName(Equilizer)

    def retranslateUi(self, Equilizer):
        Equilizer.setWindowTitle(QCoreApplication.translate("Equilizer", u"Equilizer ", None))
        self.labeldB.setText(QCoreApplication.translate("Equilizer", u"dB", None))
        self.labelpos6.setText(QCoreApplication.translate("Equilizer", u"+6", None))
        self.labelpos3.setText(QCoreApplication.translate("Equilizer", u"+3", None))
        self.labelneg3.setText(QCoreApplication.translate("Equilizer", u"-3", None))
        self.labelneg6.setText(QCoreApplication.translate("Equilizer", u"-6", None))
        self.labelzero.setText(QCoreApplication.translate("Equilizer", u"0", None))
        self.label25Hz.setText(QCoreApplication.translate("Equilizer", u"25", None))
        self.label31Hz.setText(QCoreApplication.translate("Equilizer", u"31", None))
        self.label40Hz.setText(QCoreApplication.translate("Equilizer", u"40", None))
        self.label50Hz.setText(QCoreApplication.translate("Equilizer", u"50", None))
        self.label63Hz.setText(QCoreApplication.translate("Equilizer", u"63", None))
        self.label80Hz.setText(QCoreApplication.translate("Equilizer", u"80", None))
        self.label100Hz.setText(QCoreApplication.translate("Equilizer", u"100", None))
        self.label125Hz.setText(QCoreApplication.translate("Equilizer", u"125", None))
        self.label160Hz.setText(QCoreApplication.translate("Equilizer", u"160", None))
        self.label200Hz.setText(QCoreApplication.translate("Equilizer", u"200", None))
        self.label250Hz.setText(QCoreApplication.translate("Equilizer", u"250", None))
        self.label315Hz.setText(QCoreApplication.translate("Equilizer", u"315", None))
        self.label400Hz.setText(QCoreApplication.translate("Equilizer", u"400", None))
        self.label500Hz.setText(QCoreApplication.translate("Equilizer", u"500", None))
        self.label630Hz.setText(QCoreApplication.translate("Equilizer", u"630", None))
        self.label800Hz.setText(QCoreApplication.translate("Equilizer", u"800", None))
        self.label1kHz.setText(QCoreApplication.translate("Equilizer", u"1k", None))
        self.label1k25Hz.setText(QCoreApplication.translate("Equilizer", u"1k25", None))
        self.label1k6Hz.setText(QCoreApplication.translate("Equilizer", u"1k6", None))
        self.label2kHz.setText(QCoreApplication.translate("Equilizer", u"2k", None))
        self.label2k5Hz.setText(QCoreApplication.translate("Equilizer", u"2k5", None))
        self.label3k15Hz.setText(QCoreApplication.translate("Equilizer", u"3k15", None))
        self.label4kHz.setText(QCoreApplication.translate("Equilizer", u"4k", None))
        self.label5kHz.setText(QCoreApplication.translate("Equilizer", u"5k", None))
        self.label6k3Hz.setText(QCoreApplication.translate("Equilizer", u"6k3", None))
        self.label8kHz.setText(QCoreApplication.translate("Equilizer", u"8k", None))
        self.label10kHz.setText(QCoreApplication.translate("Equilizer", u"10k", None))
        self.label12k5Hz.setText(QCoreApplication.translate("Equilizer", u"12k5", None))
        self.label16kHz.setText(QCoreApplication.translate("Equilizer", u"16k", None))
        self.label20kHz.setText(QCoreApplication.translate("Equilizer", u"20k", None))
        self.pushButtonFileBrowse.setText(QCoreApplication.translate("Equilizer", u"Browse", None))
        self.pushButtonFileImport.setText(QCoreApplication.translate("Equilizer", u"Import", None))
        self.pushButtonReset.setText(QCoreApplication.translate("Equilizer", u"Reset", None))
        self.radioButtonpolezero.setText(QCoreApplication.translate("Equilizer", u"Pole/Zero Plot", None))
        self.radioButtonfreqdom.setText(QCoreApplication.translate("Equilizer", u"Frequency Domain Plot", None))
        self.radioButtontimedom.setText(QCoreApplication.translate("Equilizer", u"Time Domain Plot", None))
        self.labelFilterPlot.setText(QCoreApplication.translate("Equilizer", u"Filter Plot", None))
        self.labelFreqPlot.setText(QCoreApplication.translate("Equilizer", u"Frequency Plot", None))
        self.labelTimePlot.setText(QCoreApplication.translate("Equilizer", u"Time Plot", None))
